import type { Product } from "@/types";

export const demoProducts = [
  {
    id: "1",
    name: "Omani Dates Premium",
    nameAr: "تمور عمانية فاخرة",
    slug: "omani-dates",
    description: "تمور عمانية طازجة من أفضل المزارع",
    price: 12.5,
    compareAtPrice: 15.0,
    currency: "OMR",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5f304c3a?w=400",
    images: ["https://images.unsplash.com/photo-1606313564200-e75d5f304c3a?w=400"],
    category: "مواد غذائية",
    storeName: "سوق مسقط",
    rating: 4.8,
    reviewsCount: 124,
    stock: 50,
    isFeatured: true,
    isOnSale: true,
  },
  {
    id: "2",
    name: "Frankincense Oil",
    nameAr: "زيت اللبان",
    slug: "frankincense-oil",
    description: "زيت لبان عماني أصلي",
    price: 8.9,
    compareAtPrice: 11.5,
    currency: "OMR",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400",
    images: ["https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400"],
    category: "جمال وعناية",
    storeName: "تراث نزوى",
    rating: 4.6,
    reviewsCount: 89,
    stock: 30,
    isOnSale: true,
  },
  {
    id: "3",
    name: "Silver Khanjar",
    nameAr: "خنجر فضي",
    slug: "silver-khanjar",
    description: "خنجر فضي يدوي الصنع",
    price: 45,
    currency: "OMR",
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400",
    images: ["https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400"],
    category: "حرف عمانية",
    storeName: "تراث نزوى",
    rating: 4.9,
    reviewsCount: 56,
    stock: 12,
    isFeatured: true,
  },
  {
    id: "4",
    name: "Omani Honey",
    nameAr: "عسل عماني",
    slug: "omani-honey",
    description: "عسل طبيعي من جبال عمان",
    price: 15.75,
    compareAtPrice: 19.0,
    currency: "OMR",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e7848ae?w=400",
    images: ["https://images.unsplash.com/photo-1587049352846-4a222e7848ae?w=400"],
    category: "مواد غذائية",
    storeName: "هدايا صلالة",
    rating: 4.7,
    reviewsCount: 203,
    stock: 25,
    isOnSale: true,
  },
  {
    id: "5",
    name: "Omani Perfume",
    nameAr: "عطر عماني",
    slug: "omani-perfume",
    description: "عطر شرقي فاخر",
    price: 28,
    compareAtPrice: 35,
    currency: "OMR",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400",
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=400"],
    category: "جمال وعناية",
    storeName: "سوق مسقط",
    rating: 4.5,
    reviewsCount: 67,
    stock: 40,
    isOnSale: true,
  },
  {
    id: "6",
    name: "Traditional Pottery",
    nameAr: "فخار تقليدي",
    slug: "traditional-pottery",
    description: "قطع فخارية عمانية يدوية",
    price: 22,
    currency: "OMR",
    image: "https://images.unsplash.com/photo-1578749556568-bc2df40c67d9?w=400",
    images: ["https://images.unsplash.com/photo-1578749556568-bc2df40c67d9?w=400"],
    category: "حرف عمانية",
    storeName: "تراث نزوى",
    rating: 4.4,
    reviewsCount: 34,
    stock: 18,
  },
] as unknown as Product[];

export const demoStores = [
  {
    id: "1",
    name: "Muscat Souq",
    nameAr: "سوق مسقط",
    slug: "muscat-souq",
    description: "أفضل المنتجات العمانية التقليدية والحديثة",
    logo: "https://ui-avatars.com/api/?name=MS&background=006400&color=fff",
    coverImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600",
    category: "تسوق عام",
    city: "مسقط",
    address: "مطرح",
    rating: 4.8,
    reviewsCount: 320,
    productsCount: 320,
    isVerified: true,
  },
  {
    id: "2",
    name: "Salalah Gifts",
    nameAr: "هدايا صلالة",
    slug: "salalah-gifts",
    description: "هدايا تذكارية ومنتجات من جنوب عمان",
    logo: "https://ui-avatars.com/api/?name=SG&background=D4AF37&color=000",
    coverImage: "https://images.unsplash.com/photo-1555529669-2269763671c8?w=600",
    category: "هدايا",
    city: "صلالة",
    rating: 4.6,
    reviewsCount: 185,
    productsCount: 185,
    isVerified: true,
  },
  {
    id: "3",
    name: "Nizwa Heritage",
    nameAr: "تراث نزوى",
    slug: "nizwa-heritage",
    description: "حرف يدوية وتراث عماني أصيل",
    logo: "https://ui-avatars.com/api/?name=NH&background=C41E3A&color=fff",
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
    category: "حرف عمانية",
    city: "نزوى",
    rating: 4.9,
    reviewsCount: 240,
    productsCount: 240,
    isVerified: true,
  },
  {
    id: "4",
    name: "Sohar Market",
    nameAr: "سوق صحار",
    slug: "sohar-market",
    description: "منتجات متنوعة بأسعار منافسة",
    logo: "https://ui-avatars.com/api/?name=SM&background=1A1A2E&color=fff",
    coverImage: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=600",
    category: "تسوق عام",
    city: "صحار",
    rating: 4.5,
    reviewsCount: 156,
    productsCount: 156,
    isVerified: false,
  },
];

export function getDemoProductBySlug(slug: string) {
  return demoProducts.find((p) => p.slug === slug) ?? null;
}

export function getDemoStoreBySlug(slug: string) {
  return demoStores.find((s) => s.slug === slug) ?? null;
}

export function getDemoProductsByStoreName(storeName: string) {
  const store = demoStores.find(
    (s) => s.name === storeName || s.nameAr === storeName
  );
  const names = store ? [store.name, store.nameAr].filter(Boolean) : [storeName];
  return demoProducts.filter(
    (p) => p.storeName != null && names.includes(p.storeName),
  );
}
